language: ruby

cache: bundler

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head

matrix:
  include:
    - rvm: 2.3.6
      script:
        - bundle exec danger
  allow_failures:
    - rvm: ruby-head
